# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gnirehtet Build

on:
  workflow_dispatch:
#   push:
#     branches: [master]
#   pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Ready
        run: |
          brew install x86_64-pc-windows-gnu

      - name: Build Gnirehtet
        run: |
          

      - name: Setup Debug Session
        uses: csexton/debugger-action@master
